### ISSUE TITLE
from utils import normalizing

### ISSUE THREAD

**Issue by lambda-ai** [guoyinwang/LEAM#1]
Hi, there seems to be some issues with the version I cloned:

Traceback (most recent call last):
  File "/home/mat/repos/tmp/LEAM/main.py", line 15, in <module>
    from model import *
  File "/home/mat/repos/tmp/LEAM/model.py", line 2, in <module>
    from utils import normalizing
ImportError: cannot import name normalizing

Indeed, there's no function "normalizing" in the utils package.

Thanks,
-Mathias

**Comment by guoyinwang** [comment]
Hi Mathias,

Thanks for pointing out. I have corrected it. Please pull the latest version.
