### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by lambda-ai** [guoyinwang/LEAM#2]
Hi,
after correcting a few small typos, I'm running into a real error, apparently related to a wrong embedding size:

Traceback (most recent call last):
  File "/home/mat/repos/tmp/LEAM/main.py", line 275, in <module>
    main()
  File "/home/mat/repos/tmp/LEAM/main.py", line 151, in main
    opt.W_class_emb =  load_class_embedding( wordtoix, opt)
  File "/home/mat/repos/tmp/LEAM/utils.py", line 90, in load_class_embedding
    value_list = [ [ opt.W_emb[i] for i in l]    for l in id_list]
IndexError: index 514556 is out of bounds for axis 0 with size 300

This is using your latest checkout and the data downloaded from your google drive.

Thanks,
-Mathias

**Comment by guoyinwang** [comment]
Thanks for pointing this out. It due mismatch of the dataset process. I have corrected the data format. Please redownload the file. Then it should work. Also, would you mind pointing out the small typos?
