### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by hanhao0125** [guoyinwang/LEAM#4]
I'm confused in somewhere，but got no reply from email，so i'm here.

In section 4.1 Model, when get the matrix G, i thought each element in G can be seen as the score between words and labels. But when you do conv and pooling, what's the meaning of result? max-pooling will lose the position information, which means you can't know the score represent which labels

Besides, how do you get the test accuracy in your paper? Choose the max valid accuracy as the final model then test in Test set?

**Comment by guoyinwang** [comment]
The conv indicates using n-gram phrase to get the attention score. The concern about pooling is reasonable, max-pooling should not be the optimal choice here. That is also the improvement we are working on for this model. 

About accuracy, you are right. We update the test accuracy when we get best valid accuracy.
